CREATE TABLE cart (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cart_items (
  id SERIAL PRIMARY KEY,
  cart_id INT REFERENCES cart(id) ON DELETE CASCADE NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1
);