auth_enabled: false

server:
  http_listen_port: 3100

compactor:
  working_directory: /loki/compactor

ingester:
  wal:
    dir: /loki/wal

limits_config:
  allow_structured_metadata: false

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

memberlist:
  join_members:
    - loki:7946
