server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Keep only containers explicitly labeled for logging
      - source_labels: [__meta_docker_container_label_log]
        regex: (?i)true
        action: keep

      # Drop logs from stderr if you deem them noisy
      - source_labels: [__meta_docker_container_log_stream]
        regex: stderr
        action: drop

      # Label each log stream by the container name
      - source_labels: [__meta_docker_container_name]
        target_label: container


      - source_labels: [__meta_docker_container_image]
        target_label: image

      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service

      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: project

      - source_labels: [__meta_docker_container_log_path]
        target_label: __path__

      - source_labels: [__meta_docker_container_label_environment]
        target_label: environment
